### ISSUE TITLE
AcceptOfferController/Logging

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#102]
Behaviour: AcceptOfferController/Logging

Annotations for the test cases:

    @TestedBehaviour("Logging")
    @TestedService("AcceptOfferController")

The production code is at com.kodekonveyor.work_request.offer.AcceptOfferController.java
The testcase base should be at com.kodekonveyor.work_request.offer.AcceptOfferControllerTestBase.java
The testcase should probably be at com.kodekonveyor.work_request.offer.AcceptOfferControllerLoggingTest.java

All activities should be logged with level INFO before anything else is done with the user initiating the activity (if known), and the name of the controller.

The result of all successful activities should be logged with level FINE the name of the controller, id(s) of the result(s) (if there is an id), or the value, using the string SUCCESS

The result of all failures should be logged with level WARNING, with the name of the controller, the string "FAILURE", and the reason of the failure.

The logging is implemented by LoggerService. All other controllers and services should call that.

If the user is not knowns, the "user" parameter must be null.

See https://www.vogella.com/tutorials/Logging/article.html for how to log.

The service:
        
AcceptOfferController
[![AcceptOfferController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/0f3e3f05-c2ca-4108-b21d-f9a941ba59c8.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#0f3e3f05-c2ca-4108-b21d-f9a941ba59c8)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    
OfferEntity
[![OfferEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/48ea499b-19cb-45b4-96c2-fb1a95a260f7.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#48ea499b-19cb-45b4-96c2-fb1a95a260f7)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by anish97IND** [comment]
grab

**Comment by magwas** [comment]
ungrabbing due to inactivity

**Comment by vendra131** [comment]
grab

**Comment by magwas** [comment]
1. You can have only one task without a pull request
2. We have made you an established coder, I'll invite you to our TaskMarket Project.

**Comment by raghavancgn** [comment]
grab

**Comment by vendra131** [comment]
> 1. You can have only one task without a pull request
> 2. We have made you an established coder, I'll invite you to our TaskMarket Project.

I have one task with PR raised
Most of the Task Market tasks seem to be implemented in ongoing PRs.

**Comment by raghavancgn** [comment]
Downloaded xml_docklet repository and switched over to java11. Also installed lombok. Thereby Environment issues resolved. Proceeding further.
