### ISSUE TITLE
MarkCompletionController/Logging

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#103]
Behaviour: MarkCompletionController/Logging

Annotations for the test cases:

    @TestedBehaviour("Logging")
    @TestedService("MarkCompletionController")

The production code is at com.kodekonveyor.completion.MarkCompletionController.java
The testcase base should be at com.kodekonveyor.completion.MarkCompletionControllerTestBase.java
The testcase should probably be at com.kodekonveyor.completion.MarkCompletionControllerLoggingTest.java

All activities should be logged with level INFO before anything else is done with the user initiating the activity (if known), and the name of the controller.

The result of all successful activities should be logged with level FINE the name of the controller, id(s) of the result(s) (if there is an id), or the value, using the string SUCCESS

The result of all failures should be logged with level WARNING, with the name of the controller, the string "FAILURE", and the reason of the failure.

The logging is implemented by LoggerService. All other controllers and services should call that.

If the user is not knowns, the "user" parameter must be null.

See https://www.vogella.com/tutorials/Logging/article.html for how to log.

The service:
        
mark work as completed
[![mark work as completed](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/3da6096d-00bc-47de-8b1e-bbfcbaa0e901.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#3da6096d-00bc-47de-8b1e-bbfcbaa0e901)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by SteveJ123** [comment]
grab

**Comment by szirbucz** [comment]
More than 1 week spent without a pull request. This issue is up for grab.

**Comment by SteveJ123** [comment]
grab

**Comment by anish97IND** [comment]
grab

**Comment by magwas** [comment]
ungrabbing due to inactivity. if you want to work on it, regrab.

**Comment by vendra131** [comment]
grab

**Comment by vendra131** [comment]
@magwas raised PR for this.
