### ISSUE TITLE
LoggerService/Logging

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#105]
Behaviour: LoggerService/Logging

Annotations for the test cases:

    @TestedBehaviour("Logging")
    @TestedService("LoggerService")

The production code is at com.kodekonveyor.logging.LoggerService.java
The testcase base should be at com.kodekonveyor.logging.LoggerServiceTestBase.java
The testcase should probably be at com.kodekonveyor.logging.LoggerServiceLoggingTest.java

All activities should be logged with level INFO before anything else is done with the user initiating the activity (if known), and the name of the controller.

The result of all successful activities should be logged with level FINE the name of the controller, id(s) of the result(s) (if there is an id), or the value, using the string SUCCESS

The result of all failures should be logged with level WARNING, with the name of the controller, the string "FAILURE", and the reason of the failure.

The logging is implemented by LoggerService. All other controllers and services should call that.

If the user is not knowns, the "user" parameter must be null.

See https://www.vogella.com/tutorials/Logging/article.html for how to log.

The service:
        
LoggerService
[![LoggerService](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/b22c9a71-522f-4b5c-a6f7-8fe3d9e14eef.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#b22c9a71-522f-4b5c-a6f7-8fe3d9e14eef)
    
DTOs and Entities:
        

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by realnaveen** [comment]
Grab

**Comment by szirbucz** [comment]
@realnaveen, the current implementation (`public void call(final String msg)`) should be removed from the logger service. Please take care of the already implemented calls.

**Comment by szirbucz** [comment]
@realnaveen 
To the proper implementation there is some help. https://medium.com/simars/inject-loggers-in-spring-java-or-kotlin-87162d02d068
You will need to add the LoggerConfiguration.java extended with an `@InterfaceClass` annotation and use the `3. Inject Logger in Beans | @Autowiring Field level injection` example in the LoggerService.

**Comment by szirbucz** [comment]
More than 1 week spent without a pull request. This issue is ungrabbed.

**Comment by magwas** [comment]
Should we close this issue?
