### ISSUE TITLE
CustomerGetWorkRequestsController/compile output

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#19]
Behaviour: CustomerGetWorkRequestsController/compile output

Annotations for the test cases:

    @TestedBehaviour("compile output")
    @TestedService("CustomerGetWorkRequestsController")

The production code is at com.kodekonveyor.work_request.open.CustomerGetWorkRequestsController.java
You should probably start at com.kodekonveyor.work_request.open.CustomerGetWorkRequestsControllerTests.java

response DTOs are newly created and the fields are filled by copying information from entities and other available data
The service:

CustomerGetWorkRequestsController
[![CustomerGetWorkRequestsController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/55cbe08c-3044-4934-875d-f583cbefca24.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#55cbe08c-3044-4934-875d-f583cbefca24)

DTOs and Entities:

WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), ask on the [Telegram channel](https://t.me/joinchat/D1deE0loEBoFGvyDssWRuw) or ask your mentor.

**Comment by rameshthumati22** [comment]
grabed

**Comment by rameshthumati22** [comment]
This is already done
