### ISSUE TITLE
FindWorkRequestController/compile output

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#21]
Behaviour: FindWorkRequestController/compile output

Annotations for the test cases:

    @TestedBehaviour("compile output")
    @TestedService("FindWorkRequestController")

The production code is at com.kodekonveyor.work_request.find.FindWorkRequestController.java
You should probably start at com.kodekonveyor.work_request.find.FindWorkRequestControllerTests.java

response DTOs are newly created and the fields are filled by copying information from entities and other available data
The service:

FindWorkRequestController
[![FindWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/d0a6f3ba-3c3b-4756-be88-c86365f53695.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#d0a6f3ba-3c3b-4756-be88-c86365f53695)

DTOs and Entities:

WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)

WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), ask on the [Telegram channel](https://t.me/joinchat/D1deE0loEBoFGvyDssWRuw) or ask your mentor.

**Comment by rameshthumati22** [comment]
grabed

**Comment by rameshthumati22** [comment]
It is already done
