### ISSUE TITLE
CreateWorkRequestController/Save the new/modified entities

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#22]
Behaviour: CreateWorkRequestController/Save the new/modified entities

Annotations for the test cases:

    @TestedBehaviour("Save the new/modified entities")
    @TestedService("CreateWorkRequestController")

The production code is at com.kodekonveyor.work_request.create.CreateWorkRequestController.java
You should probably start at com.kodekonveyor.work_request.create.CreateWorkRequestControllerTests.java

new/modified entities should be saved using the save() method of the corresponding repository.
The service:

CreateWorkRequestController
[![CreateWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/3c59b07f-3960-44c1-8815-9fd3684b1ba4.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#3c59b07f-3960-44c1-8815-9fd3684b1ba4)

DTOs and Entities:

CreateWorkRequestDTO
[![CreateWorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/4989cb72-036c-4cb0-bcca-6f87c6566eb1.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#4989cb72-036c-4cb0-bcca-6f87c6566eb1)

WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), ask on the [Telegram channel](https://t.me/joinchat/D1deE0loEBoFGvyDssWRuw) or ask your mentor.

**Comment by praveen171987** [comment]
grabed

**Comment by magwas** [comment]
Already implemented
