### ISSUE TITLE
RevokeWorkRequestController/Save the new/modified entities

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#23]
Behaviour: RevokeWorkRequestController/Save the new/modified entities

Annotations for the test cases:

    @TestedBehaviour("Save the new/modified entities")
    @TestedService("RevokeWorkRequestController")

The production code is at com.kodekonveyor.work_request.revoke.RevokeWorkRequestController.java
You should probably start at com.kodekonveyor.work_request.revoke.RevokeWorkRequestControllerTests.java

new/modified entities should be saved using the save() method of the corresponding repository.
The service:

RevokeWorkRequestController
[![RevokeWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/d84d88ac-53d1-4597-b14b-25719d1e3133.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#d84d88ac-53d1-4597-b14b-25719d1e3133)

DTOs and Entities:

WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), ask on the [Telegram channel](https://t.me/joinchat/D1deE0loEBoFGvyDssWRuw) or ask your mentor.

**Comment by rameshthumati22** [comment]
grabed

**Comment by akash11235** [comment]
grab

**Comment by szirbucz** [comment]
More than a week spent without pull request. Issue is up for grab.

**Comment by sushmavejamdla** [comment]
Grab

**Comment by magwas** [comment]
ungrabbing due to inactivity

**Comment by raghavancgn** [comment]
grab

**Comment by raghavancgn** [comment]
Recreated the KK dev env on my desktop (a newly upgraded). Started on the work.

**Comment by magwas** [comment]
The behaviour is duplicate. It is a design error.
