### ISSUE TITLE
CustomerGetWorkRequestsController/input validation

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#25]
Behaviour: CustomerGetWorkRequestsController/input validation

    @TestedBehaviour("input validation")
    @TestedService("CustomerGetWorkRequestsController")

You should modify .CustomerGetWorkRequestsController.

            All input is validated before any other processing.
The validation rules of entity fields are described at the corresponding entity field documentation.
Error is signaled by throwing ValidationException, with the message detailing the business meaning and value of the bad value, along with description of the accepted inputs

Relevant views:
            
[![Behaviours](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/685e0e46-a4f5-4fbc-9fdd-2548b5618112.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/685e0e46-a4f5-4fbc-9fdd-2548b5618112.png)
    
[![CreateWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/3c59b07f-3960-44c1-8815-9fd3684b1ba4.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/3c59b07f-3960-44c1-8815-9fd3684b1ba4.png)
    
[![CustomerGetWorkRequestsController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/55cbe08c-3044-4934-875d-f583cbefca24.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/55cbe08c-3044-4934-875d-f583cbefca24.png)
    
[![OpenWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/8a1e2c2c-bb06-4c1d-a847-d376586be5cc.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/8a1e2c2c-bb06-4c1d-a847-d376586be5cc.png)
    
[![FindWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/d0a6f3ba-3c3b-4756-be88-c86365f53695.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/d0a6f3ba-3c3b-4756-be88-c86365f53695.png)
    
[![RevokeWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/d84d88ac-53d1-4597-b14b-25719d1e3133.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/d84d88ac-53d1-4597-b14b-25719d1e3133.png)
    

More about the service:
            
More about the behaviour:
            

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), ask on the [Telegram channel](https://t.me/joinchat/D1deE0loEBoFGvyDssWRuw) or ask your mentor.

**Comment by Mayuresh94** [comment]
grab
