### ISSUE TITLE
OpenWorkRequestController/input validation

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#26]
Behaviour: OpenWorkRequestController/input validation

Annotations for the test cases:

    @TestedBehaviour("input validation")
    @TestedService("OpenWorkRequestController")

The production code is at com.kodekonveyor.work_request.open.OpenWorkRequestController.java
The test base is at com.kodekonveyor.work_request.open.OpenWorkRequestControllerTestBase.java
You should probably work on com.kodekonveyor.work_request.open.OpenWorkRequestControllerInputValidationTest.java

All input is validated before any other processing.
The validation rules of entity fields are described at the corresponding entity field documentation.
Error is signaled by throwing ValidationException, with the message detailing the business meaning and value of the bad value, along with description of the accepted inputs

The service:
        
OpenWorkRequestController
[![OpenWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/8a1e2c2c-bb06-4c1d-a847-d376586be5cc.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#8a1e2c2c-bb06-4c1d-a847-d376586be5cc)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), ask on the [Telegram channel](https://t.me/joinchat/D1deE0loEBoFGvyDssWRuw) or ask your mentor.

**Comment by Mayuresh94** [comment]
Grab
