### ISSUE TITLE
CreateWorkRequestController/Data access

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#30]
Behaviour: CreateWorkRequestController/Data access

Annotations for the test cases:

    @TestedBehaviour("Data access")
    @TestedService("CreateWorkRequestController")

The production code is at com.kodekonveyor.work_request.create.CreateWorkRequestController.java
You should probably start at com.kodekonveyor.work_request.create.CreateWorkRequestControllerTests.java

Entities are

- created using the constructor of the entity. Created entities should be saved by the save() method of the corresponding repository
- retrieved using the query methods of the corresponding repository
- updated using setters of the entity. updated entities should be saved (see above)
- deleted using the delete() method of the corresponding repository

The service:

CreateWorkRequestController
[![CreateWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/3c59b07f-3960-44c1-8815-9fd3684b1ba4.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#3c59b07f-3960-44c1-8815-9fd3684b1ba4)

DTOs and Entities:

CreateWorkRequestDTO
[![CreateWorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/4989cb72-036c-4cb0-bcca-6f87c6566eb1.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#4989cb72-036c-4cb0-bcca-6f87c6566eb1)

WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), ask on the [Telegram channel](https://t.me/joinchat/D1deE0loEBoFGvyDssWRuw) or ask your mentor.

**Comment by Shubhamd13** [comment]
grab
