### ISSUE TITLE
CustomerGetWorkRequestsController/Data access

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#31]
Behaviour: CustomerGetWorkRequestsController/Data access

Annotations for the test cases:

    @TestedBehaviour("Data access")
    @TestedService("CustomerGetWorkRequestsController")

The production code is at com.kodekonveyor.work_request.open.CustomerGetWorkRequestsController.java
You should probably start at com.kodekonveyor.work_request.open.CustomerGetWorkRequestsControllerTests.java

Entities are

- created using the constructor of the entity. Created entities should be saved by the save() method of the corresponding repository
- retrieved using the query methods of the corresponding repository
- updated using setters of the entity. updated entities should be saved (see above)
- deleted using the delete() method of the corresponding repository

The service:

CustomerGetWorkRequestsController
[![CustomerGetWorkRequestsController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/55cbe08c-3044-4934-875d-f583cbefca24.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#55cbe08c-3044-4934-875d-f583cbefca24)

DTOs and Entities:

WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), ask on the [Telegram channel](https://t.me/joinchat/D1deE0loEBoFGvyDssWRuw) or ask your mentor.

**Comment by Mayuresh94** [comment]
grab
