### ISSUE TITLE
OpenWorkRequestController/Data access

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#32]
Behaviour: OpenWorkRequestController/Data access

Annotations for the test cases:

    @TestedBehaviour("Data access")
    @TestedService("OpenWorkRequestController")

The production code is at com.kodekonveyor.work_request.open.OpenWorkRequestController.java
You should probably start at com.kodekonveyor.work_request.open.OpenWorkRequestControllerTests.java

Entities are

- created using the constructor of the entity. Created entities should be saved by the save() method of the corresponding repository
- retrieved using the query methods of the corresponding repository
- updated using setters of the entity. updated entities should be saved (see above)
- deleted using the delete() method of the corresponding repository

The service:
        
OpenWorkRequestController
[![OpenWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/8a1e2c2c-bb06-4c1d-a847-d376586be5cc.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#8a1e2c2c-bb06-4c1d-a847-d376586be5cc)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), ask on the [Telegram channel](https://t.me/joinchat/D1deE0loEBoFGvyDssWRuw) or ask your mentor.

**Comment by Shubhamd13** [comment]
grabbed
