### ISSUE TITLE
RevokeWorkRequestController/Data access

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#34]
Behaviour: RevokeWorkRequestController/Data access

Annotations for the test cases:

    @TestedBehaviour("Data access")
    @TestedService("RevokeWorkRequestController")

The production code is at com.kodekonveyor.work_request.revoke.RevokeWorkRequestController.java
The testcase base should be at com.kodekonveyor.work_request.revoke.RevokeWorkRequestControllerTestBase.java
The testcase should probably be at com.kodekonveyor.work_request.revoke.RevokeWorkRequestControllerDataAccessTest.java

Entities are

- created using the constructor of the entity. Created entities should be saved by the save() method of the corresponding repository
- retrieved using the query methods of the corresponding repository
- updated using setters of the entity. updated entities should be saved (see above)
- deleted using the delete() method of the corresponding repository

The service:
	
RevokeWorkRequestController
[![RevokeWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/d84d88ac-53d1-4597-b14b-25719d1e3133.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#d84d88ac-53d1-4597-b14b-25719d1e3133)
    
DTOs and Entities:
	
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by rameshthumati22** [comment]
grabed

**Comment by Meenal2020** [comment]
grab
