### ISSUE TITLE
GiveofferController/compile output

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#53]
Behaviour: GiveofferController/compile output

Annotations for the test cases:

    @TestedBehaviour("compile output")
    @TestedService("GiveofferController")

The production code is at com.kodekonveyor.work_request.offer.GiveofferController.java
The testcase base should be at com.kodekonveyor.work_request.offer.GiveofferControllerTestBase.java
The testcase should probably be at com.kodekonveyor.work_request.offer.GiveofferControllerCompileOutputTest.java

response DTOs are newly created and the fields are filled by copying information from entities and other available data
The service:
        
GiveOfferController
[![GiveOfferController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/804ebf29-0ea5-4509-8de8-795371093f4a.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#804ebf29-0ea5-4509-8de8-795371093f4a)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
OfferDTO
[![OfferDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/86f71c79-a953-40ea-ac57-5db3a1e639d8.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#86f71c79-a953-40ea-ac57-5db3a1e639d8)
    
OfferEntity
[![OfferEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/48ea499b-19cb-45b4-96c2-fb1a95a260f7.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#48ea499b-19cb-45b4-96c2-fb1a95a260f7)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by JinLei324** [comment]
grab

**Comment by JinLei324** [comment]
GiveofferController compileoutput 
https://github.com/JinLei324/tidy-up/commit/0275628cb26b1e9227e7408663f7d3a568c13860

**Comment by Meenal2020** [comment]
part of this development is already covered in the development of #54(which is already done), hence would like to grab this task.

**Comment by szirbucz** [comment]
More than 1 week spent without a pull request. This issue is up for grab.

**Comment by Meenal2020** [comment]
Hi, The code changes and pull request has been reviewed/approved and merged. I don't think there is any work remaining on this task. Please recheck.
