### ISSUE TITLE
RevokeWorkRequestController/access control

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#55]
Behaviour: RevokeWorkRequestController/access control

Annotations for the test cases:

    @TestedBehaviour("access control")
    @TestedService("RevokeWorkRequestController")

The production code is at com.kodekonveyor.work_request.revoke.RevokeWorkRequestController.java
The testcase base should be at com.kodekonveyor.work_request.revoke.RevokeWorkRequestControllerTestBase.java
The testcase should probably be at com.kodekonveyor.work_request.revoke.RevokeWorkRequestControllerAccessControlTest.java

* a user can only revoke its own work request
* a user can only accept an offer for its own work request
The service:
        
RevokeWorkRequestController
[![RevokeWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/d84d88ac-53d1-4597-b14b-25719d1e3133.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#d84d88ac-53d1-4597-b14b-25719d1e3133)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by Mayuresh94** [comment]
grab

**Comment by pthakkar02** [comment]
Grab.
