### ISSUE TITLE
MarkCompletionController/compile output

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#65]
Behaviour: MarkCompletionController/compile output

Annotations for the test cases:

    @TestedBehaviour("compile output")
    @TestedService("MarkCompletionController")

The production code is at com.kodekonveyor.completion.MarkCompletionController.java
The testcase base should be at com.kodekonveyor.completion.MarkCompletionControllerTestBase.java
The testcase should probably be at com.kodekonveyor.completion.MarkCompletionControllerCompileOutputTest.java

response DTOs are newly created and the fields are filled by copying information from entities and other available data
The service:
        
mark work as completed
[![mark work as completed](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/3da6096d-00bc-47de-8b1e-bbfcbaa0e901.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#3da6096d-00bc-47de-8b1e-bbfcbaa0e901)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by Lucifernit** [comment]
grab

**Comment by szirbucz** [comment]
More than 1 week spent without a pull request. This issue is up for grab.

**Comment by Lucifernit** [comment]
grab
