### ISSUE TITLE
CustomerGetWorkRequestsController/access control

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#67]
Behaviour: CustomerGetWorkRequestsController/access control

Annotations for the test cases:

    @TestedBehaviour("access control")
    @TestedService("CustomerGetWorkRequestsController")

The production code is at com.kodekonveyor.work_request.open.CustomerGetWorkRequestsController.java
The testcase base should be at com.kodekonveyor.work_request.open.CustomerGetWorkRequestsControllerTestBase.java
The testcase should probably be at com.kodekonveyor.work_request.open.CustomerGetWorkRequestsControllerAccessControlTest.java

* a user can only revoke its own work request
* a user can only accept an offer for its own work request
* a user can only list its own work request with CustomerGetWorkRequestsController

The service:
        
CustomerGetWorkRequestsController
[![CustomerGetWorkRequestsController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/55cbe08c-3044-4934-875d-f583cbefca24.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#55cbe08c-3044-4934-875d-f583cbefca24)
    
DTOs and Entities:
        
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by pthakkar02** [comment]
Grab

**Comment by pthakkar02** [comment]
This is already addressed. 
CustomerGetWorkRequestsController.call()

 final List<WorkRequestEntity> requests =
        workRequestRepository.findByCustomer(user.get());

**Comment by magwas** [comment]
testcases=1
please fill in https://docs.google.com/forms/d/e/1FAIpQLSdNMbUDPHp2CCbsKtx3qMDCGXIYmmRsjJoF201Xtl-xvb2llQ/viewform

**Comment by magwas** [comment]
This is already implemented. Your job is to create the test class with the appropriate name and annotations, and move the related test case there.
We pay one testcase for it.

**Comment by devasuryar** [comment]
grab

**Comment by SteveJ123** [comment]
grab

**Comment by magwas** [comment]
ungrabbed due to inactivity

**Comment by vendra131** [comment]
grab

**Comment by vendra131** [comment]
@magwas  PR raised.
