### ISSUE TITLE
FindWorkRequestController/statuses

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#69]
Behaviour: FindWorkRequestController/statuses

Annotations for the test cases:

    @TestedBehaviour("statuses")
    @TestedService("FindWorkRequestController")

The production code is at com.kodekonveyor.work_request.find.FindWorkRequestController.java
The testcase base should be at com.kodekonveyor.work_request.find.FindWorkRequestControllerTestBase.java
The testcase should probably be at com.kodekonveyor.work_request.find.FindWorkRequestControllerStatusesTest.java

a posted work request is in the POSTED status
when an offer is accepted, it changes status to be AGREED
when the provider marks an AGREED work as completed its status becomes COMPLETED
when the customer marks a COMPLETED work as completed, it becomes VERIFIED
when the customer marks a VERIFIED work as paid, it becomes PAID
when the customer marks a PAID work as pid, it becomes CLOSED

No other state transition is allowed

When the work request is not in POSTED status, only its customer and provider can access it.

The service:
        
FindWorkRequestController
[![FindWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/d0a6f3ba-3c3b-4756-be88-c86365f53695.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#d0a6f3ba-3c3b-4756-be88-c86365f53695)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by debd440** [comment]
Grab

**Comment by szirbucz** [comment]
More than 1 week spent without a pull request. This issue is up for grab.

**Comment by ajay74984** [comment]
grab
