### ISSUE TITLE
AcceptOfferController/statuses

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#70]
Behaviour: AcceptOfferController/statuses

Annotations for the test cases:

    @TestedBehaviour("statuses")
    @TestedService("AcceptOfferController")

The production code is at com.kodekonveyor.work_request.offer.AcceptOfferController.java
The testcase base should be at com.kodekonveyor.work_request.offer.AcceptOfferControllerTestBase.java
The testcase should probably be at com.kodekonveyor.work_request.offer.AcceptOfferControllerStatusesTest.java

a posted work request is in the POSTED status
when an offer is accepted, it changes status to be AGREED
when the provider marks an AGREED work as completed its status becomes COMPLETED
when the customer marks a COMPLETED work as completed, it becomes VERIFIED
when the customer marks a VERIFIED work as paid, it becomes PAID
when the customer marks a PAID work as pid, it becomes CLOSED

No other state transition is allowed

When the work request is not in POSTED status, only its customer and provider can access it.

The service:
        
AcceptOfferController
[![AcceptOfferController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/0f3e3f05-c2ca-4108-b21d-f9a941ba59c8.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#0f3e3f05-c2ca-4108-b21d-f9a941ba59c8)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    
OfferEntity
[![OfferEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/48ea499b-19cb-45b4-96c2-fb1a95a260f7.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#48ea499b-19cb-45b4-96c2-fb1a95a260f7)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by sriniatgit** [comment]
grab

**Comment by Sumit9669** [comment]
grab

**Comment by szirbucz** [comment]
More than 1 week spent without a pull request. This issue is up for grab.

**Comment by anish97IND** [comment]
grab

**Comment by jitesh004** [comment]
Grab

**Comment by anish97IND** [comment]
> Grab

Hi Jitesh,
Actually I was waiting for the task to be assigned. I had commented grab just yesterday. Please check comments before posting a grab. Thank You!

**Comment by anish97IND** [comment]
Hi, This issue has been resolved and pull has been merged already.
