### ISSUE TITLE
MarkCompletionController/statuses

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#71]
Behaviour: MarkCompletionController/statuses

Annotations for the test cases:

    @TestedBehaviour("statuses")
    @TestedService("MarkCompletionController")

The production code is at com.kodekonveyor.completion.MarkCompletionController.java
The testcase base should be at com.kodekonveyor.completion.MarkCompletionControllerTestBase.java
The testcase should probably be at com.kodekonveyor.completion.MarkCompletionControllerStatusesTest.java

a posted work request is in the POSTED status
when an offer is accepted, it changes status to be AGREED
when the provider marks an AGREED work as completed its status becomes COMPLETED
when the customer marks a COMPLETED work as completed, it becomes VERIFIED
when the customer marks a VERIFIED work as paid, it becomes PAID
when the customer marks a PAID work as pid, it becomes CLOSED

No other state transition is allowed

When the work request is not in POSTED status, only its customer and provider can access it.

The service:
        
mark work as completed
[![mark work as completed](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/3da6096d-00bc-47de-8b1e-bbfcbaa0e901.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#3da6096d-00bc-47de-8b1e-bbfcbaa0e901)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by oloyedeolad** [comment]
grab

**Comment by gplkrnkr** [comment]
grab

**Comment by szirbucz** [comment]
More than 1 week spent without a pull request. This issue is up for grab.

**Comment by mayankus** [comment]
grab

**Comment by szirbucz** [comment]
Administration problem. The issue is already done.

**Comment by magwas** [comment]
@szirbucz the CI says it is not done, and we do not have a MarkCompletionControllerStatusesTest

**Comment by ajay74984** [comment]
grab

**Comment by Mayuresh94** [comment]
> grab

Please grab only one task at a time. I see you have grabbed 3 at once, with no pull requests for any of grabbed tasks.

**Comment by murugaraj30** [comment]
grab

**Comment by ajay74984** [comment]
@Mayuresh94: Please get your facts right before posting, 

![image](https://user-images.githubusercontent.com/51405689/79047042-a48b3c80-7c14-11ea-8303-7ad0e6115bb0.png)

Bdw, Am I answerable to you? @magwas please clarify?

**Comment by magwas** [comment]
I do not see tasks assigned to Ajay.

**Comment by ajay74984** [comment]
@magwas  @murugaraj30  how come, two people, are allowed to work on same issue? I have already spent the time writing test cases and  I come to know its been already merged wheres it was assigned to me?
![image](https://user-images.githubusercontent.com/51405689/79690906-4f2add00-825d-11ea-9738-24a95f65295e.png)

**Comment by magwas** [comment]
@ajay74984 thank you for the heads up. The task is grabbed by you, so you are entitled to deliver it.
In the meantime @murugaraj30 is entitled to issue a pull request and get the pull request reviewed, but not for the payment, as the task is not grabbed by him.
I have made the mistake to merge the wrong pull request.
We will discuss the exact way to straighten it up at the standup on Monday.
We will probably provide you a way to deliver the task.

I have created the branch develop_at_aa167f8, which is the point in develop before I merged the wrong pull request. You can issue your pull request against that branch, and we will consider its status when we will decide on the exact way to resolve it. As I do not find your pull request for this issue, it would help a lot in the decision if we could have one at the time of the standup (Monday 9:30 CET).

**Comment by ajay74984** [comment]
@magwas thanks for the quick response. I understand things were mixed up. and thanks for creating a branch to give me another opportunity to continue working on the task.

Having said that, it would be unfair for @murugaraj30, not getting paid for his work/time spent. I would request would you to please consider his pull request for the entitlement of the payment and we can work on any other task.  I hope this is OK with you?

**Comment by magwas** [comment]
@ajay74984 as I understood, you said that you pass this task to @murugaraj30, and you work on another task. In this case we pay @murugaraj30 for this task, and not you.
Please confirm that I understood it correctly.

**Comment by ajay74984** [comment]
@magwas correct.

**Comment by magwas** [comment]
Thank you for your considerate approach, @ajay74984

**Comment by murugaraj30** [comment]
Hi @magwas<https://github.com/magwas> and @ajay74984<mailto:notifications@github.com>,
    I worked on issue #71 ( MarkCompletionController/statuses) but it was labelled as issue #103 by mistake and later was updated to the correct issue, and also the issue was grabbed with the help of the mentor, so not quite sure where it got mixed up.
I would also like to thank @ajay74984<mailto:notifications@github.com> ,it’s a really sweet gesture from him. This is going to increase the understanding between the developers in kodekonveyor community.
Moving on hoping that we’ll avoid these kind of mix-ups in the future.
Kind Regards,
Murugaraj.
