### ISSUE TITLE
MarkAsPaidController/statuses

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#72]
Behaviour: MarkAsPaidController/statuses

Annotations for the test cases:

    @TestedBehaviour("statuses")
    @TestedService("MarkAsPaidController")

The production code is at com.kodekonveyor.completion.MarkAsPaidController.java
The testcase base should be at com.kodekonveyor.completion.MarkAsPaidControllerTestBase.java
The testcase should probably be at com.kodekonveyor.completion.MarkAsPaidControllerStatusesTest.java

a posted work request is in the POSTED status
when an offer is accepted, it changes status to be AGREED
when the provider marks an AGREED work as completed its status becomes COMPLETED
when the customer marks a COMPLETED work as completed, it becomes VERIFIED
when the customer marks a VERIFIED work as paid, it becomes PAID
when the customer marks a PAID work as pid, it becomes CLOSED

No other state transition is allowed

When the work request is not in POSTED status, only its customer and provider can access it.

The service:
        
mark work as paid
[![mark work as paid](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/dc869bc9-68f3-45b9-acde-53d5306a674a.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#dc869bc9-68f3-45b9-acde-53d5306a674a)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by szirbucz** [comment]
@magwas WorkRequestEntity & DTO have no status fields in the model.

**Comment by magwas** [comment]
The entity does have status field. I add it to the DTO.

**Comment by szirbucz** [comment]
![image](https://user-images.githubusercontent.com/8093720/72442597-1803e600-37ad-11ea-8dae-ad16aa412c63.png)

**Comment by szirbucz** [comment]
I guess isActive should be replaced by status and it should be an enum.

**Comment by magwas** [comment]
If you click on the image here, you will get to the model, where it is updated. Github shows some older version.

**Comment by szirbucz** [comment]
> If you click on the image here, you will get to the model, where it is updated. Github shows some older version.

Can't we somehow update it in the task descriptions too?

**Comment by magwas** [comment]
I did a shift-reload on the issue and now I see the right image.

**Comment by szirbucz** [comment]
OK, than I will suggest it to my mentees too.

**Comment by szirbucz** [comment]
@parvinder09, please write the following comment here: grab

**Comment by parvinder09** [comment]
grab
