### ISSUE TITLE
AcceptOfferController/accepted offer

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#73]
Behaviour: AcceptOfferController/accepted offer

Annotations for the test cases:

    @TestedBehaviour("accepted offer")
    @TestedService("AcceptOfferController")

The production code is at com.kodekonveyor.work_request.offer.AcceptOfferController.java
The testcase base should be at com.kodekonveyor.work_request.offer.AcceptOfferControllerTestBase.java
The testcase should probably be at com.kodekonveyor.work_request.offer.AcceptOfferControllerAcceptedOfferTest.java

When an offer is accepted, the provider of the offer entity  is set as the provider of the work request entity

The service:
        
AcceptOfferController
[![AcceptOfferController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/0f3e3f05-c2ca-4108-b21d-f9a941ba59c8.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#0f3e3f05-c2ca-4108-b21d-f9a941ba59c8)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    
OfferEntity
[![OfferEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/48ea499b-19cb-45b4-96c2-fb1a95a260f7.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#48ea499b-19cb-45b4-96c2-fb1a95a260f7)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by neodevan** [comment]
grab

**Comment by saidsryheni** [comment]
grab

**Comment by szirbucz** [comment]
More than 1 week spent without a pull request. This issue is up for grab.

**Comment by jitesh004** [comment]
Grab

**Comment by magwas** [comment]
ungrabbed due to inactivity

**Comment by parvinder09** [comment]
grab
