### ISSUE TITLE
CreateWorkRequestController/Logging

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#96]
Behaviour: CreateWorkRequestController/Logging

Annotations for the test cases:

    @TestedBehaviour("Logging")
    @TestedService("CreateWorkRequestController")

The production code is at com.kodekonveyor.work_request.create.CreateWorkRequestController.java
The testcase base should be at com.kodekonveyor.work_request.create.CreateWorkRequestControllerTestBase.java
The testcase should probably be at com.kodekonveyor.work_request.create.CreateWorkRequestControllerLoggingTest.java

All activities should be logged with level INFO before anything else is done with the user initiating the activity (if known), and the name of the controller.

The result of all successful activities should be logged with level FINE the name of the controller, id(s) of the result(s) (if there is an id), or the value, using the string SUCCESS

The result of all failures should be logged with level WARNING, with the name of the controller, the string "FAILURE", and the reason of the failure.

The logging is implemented by LoggerService. All other controllers and services should call that.

If the user is not knowns, the "user" parameter must be null.

See https://www.vogella.com/tutorials/Logging/article.html for how to log.

The service:
        
CreateWorkRequestController
[![CreateWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/3c59b07f-3960-44c1-8815-9fd3684b1ba4.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#3c59b07f-3960-44c1-8815-9fd3684b1ba4)
    
DTOs and Entities:
        
CreateWorkRequestDTO
[![CreateWorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/4989cb72-036c-4cb0-bcca-6f87c6566eb1.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#4989cb72-036c-4cb0-bcca-6f87c6566eb1)
    
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by Mayuresh94** [comment]
grab
