### ISSUE TITLE
CustomerGetWorkRequestsController/Logging

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#97]
Behaviour: CustomerGetWorkRequestsController/Logging

Annotations for the test cases:

    @TestedBehaviour("Logging")
    @TestedService("CustomerGetWorkRequestsController")

The production code is at com.kodekonveyor.work_request.open.CustomerGetWorkRequestsController.java
The testcase base should be at com.kodekonveyor.work_request.open.CustomerGetWorkRequestsControllerTestBase.java
The testcase should probably be at com.kodekonveyor.work_request.open.CustomerGetWorkRequestsControllerLoggingTest.java

All activities should be logged with level INFO before anything else is done with the user initiating the activity (if known), and the name of the controller.

The result of all successful activities should be logged with level FINE the name of the controller, id(s) of the result(s) (if there is an id), or the value, using the string SUCCESS

The result of all failures should be logged with level WARNING, with the name of the controller, the string "FAILURE", and the reason of the failure.

The logging is implemented by LoggerService. All other controllers and services should call that.

If the user is not knowns, the "user" parameter must be null.

See https://www.vogella.com/tutorials/Logging/article.html for how to log.

The service:
        
CustomerGetWorkRequestsController
[![CustomerGetWorkRequestsController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/55cbe08c-3044-4934-875d-f583cbefca24.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#55cbe08c-3044-4934-875d-f583cbefca24)
    
DTOs and Entities:
        
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by AnagheemAzzam** [comment]
grab

**Comment by magwas** [comment]
ungrabbed due to inactivity. please regrab if you want to continue work on this.

**Comment by vendra131** [comment]
grab

**Comment by magwas** [comment]
According to our grab rules, you can grab a task if you already have a pull request for each of your in progress tasks.

**Comment by vendra131** [comment]
grab

**Comment by vendra131** [comment]
@magwas Raised PR

**Comment by vendra131** [comment]
@magwas Removed the unnecessary logging as requested and updated PR
