### ISSUE TITLE
FindWorkRequestController/Logging

### ISSUE THREAD

**Issue by magwas** [kode-konveyor/tidy-up#99]
Behaviour: FindWorkRequestController/Logging

Annotations for the test cases:

    @TestedBehaviour("Logging")
    @TestedService("FindWorkRequestController")

The production code is at com.kodekonveyor.work_request.find.FindWorkRequestController.java
The testcase base should be at com.kodekonveyor.work_request.find.FindWorkRequestControllerTestBase.java
The testcase should probably be at com.kodekonveyor.work_request.find.FindWorkRequestControllerLoggingTest.java

All activities should be logged with level INFO before anything else is done with the user initiating the activity (if known), and the name of the controller.

The result of all successful activities should be logged with level FINE the name of the controller, id(s) of the result(s) (if there is an id), or the value, using the string SUCCESS

The result of all failures should be logged with level WARNING, with the name of the controller, the string "FAILURE", and the reason of the failure.

The logging is implemented by LoggerService. All other controllers and services should call that.

If the user is not knowns, the "user" parameter must be null.

See https://www.vogella.com/tutorials/Logging/article.html for how to log.

The service:
        
FindWorkRequestController
[![FindWorkRequestController](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/d0a6f3ba-3c3b-4756-be88-c86365f53695.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#d0a6f3ba-3c3b-4756-be88-c86365f53695)
    
DTOs and Entities:
        
WorkRequestEntity
[![WorkRequestEntity](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/f1dbf91b-ff5f-4b48-871b-696004fca51c.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#f1dbf91b-ff5f-4b48-871b-696004fca51c)
    
WorkRequestDTO
[![WorkRequestDTO](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/pics/ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd.png)](https://repository.kodekonveyor.com/tidy-up/kode-konveyor/develop/index.html#ba99b0cd-b783-4fe4-966f-0fd5c4d99fcd)
    

If you have questions, see the [FAQ](https://kodekonveyor.com/coder-faq/), or ask on the [development slack channel](https://app.slack.com/client/TDHQX8Q66/CH9KFMCMU/thread/GKCB5T7CJ-1567418169.000200) or ask your mentor.

**Comment by ayushmishra206** [comment]
Grab

**Comment by szirbucz** [comment]
More than 1 week spent without a pull request. This issue is up for grab.

**Comment by marijo31993** [comment]
grab

**Comment by magwas** [comment]
ungrabbed due to inactivity

**Comment by ajay74984** [comment]
grab

**Comment by magwas** [comment]
ungrabbing due to inactivity

**Comment by ajay74984** [comment]
grab, just need to solve merge conflict. PR 137 was hanging for weeks to be merged (there was no conflict when I push PR), when you checked there were new commits meanwhile and you could see merge conflict. 
Anyway, I will resolve to merge conflict

**Comment by raghavancgn** [comment]
grab

**Comment by szirbucz** [comment]
Ungrabbed due to inactivity for more than 13 days

**Comment by vendra131** [comment]
grab
